table 'IMPLEMENTACION BOARD'
	lineageTag: 2e534295-93ac-4879-8b27-cd41000c291d

	column Cliente
		dataType: string
		lineageTag: 0a66b81f-7689-436f-9bfc-7ce061b1d617
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column 'Plan Contratado'
		dataType: string
		lineageTag: aeb09cc7-8bbe-4f5c-a681-e8b2034ecbef
		summarizeBy: none
		sourceColumn: Plan Contratado

		annotation SummarizationSetBy = Automatic

	column Seniority
		dataType: string
		lineageTag: 40125fa1-e126-4dfa-909d-311447c6605f
		summarizeBy: none
		sourceColumn: Seniority

		annotation SummarizationSetBy = Automatic

	column Rubro
		dataType: string
		lineageTag: a7ecef30-30fe-44ba-9dfa-6166bf3e20b0
		summarizeBy: none
		sourceColumn: Rubro

		annotation SummarizationSetBy = Automatic

	column 'Persona de Contacto'
		dataType: string
		lineageTag: 1b49ec93-9781-4a72-8194-120412eb7c96
		summarizeBy: none
		sourceColumn: Persona de Contacto

		annotation SummarizationSetBy = Automatic

	column 'Board Column'
		dataType: string
		lineageTag: 4c8fd224-130a-4097-b6b8-64c072b8a6c9
		summarizeBy: none
		sourceColumn: Board Column

		annotation SummarizationSetBy = Automatic

	column 'Fecha de Contratacion'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8c6bd940-9e1f-4412-8994-76ca8e5bcc29
		summarizeBy: none
		sourceColumn: Fecha de Contratacion

		variation Variación
			isDefault
			relationship: 99aac568-0aaa-4377-bebd-977bd028fba9
			defaultHierarchy: LocalDateTable_404e0d1a-94f7-412a-b39a-9c1a2ca6b3c1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de Inicio'
		dataType: dateTime
		formatString: Short Date
		lineageTag: c204ac59-0f36-4dcc-8d15-ae32f02d4d13
		summarizeBy: none
		sourceColumn: Fecha de Inicio

		variation Variación
			isDefault
			relationship: 8f14329d-e87c-465c-96f7-bf9d968cfb4a
			defaultHierarchy: LocalDateTable_aaeb362a-4ee5-42a8-9db1-949eb4a8f42b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha inicio Fase 1'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 60176e0e-9ace-4543-be2a-17bdd5d051db
		summarizeBy: none
		sourceColumn: Fecha inicio Fase 1

		variation Variación
			isDefault
			relationship: 504d89b8-9ecf-4e48-a774-736c8a7804a0
			defaultHierarchy: LocalDateTable_82431003-6baf-462d-8067-216b4d296d63.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha Implementado'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8aac1155-a853-45d0-ab7e-d1b03c40dbdf
		summarizeBy: none
		sourceColumn: Fecha Implementado

		variation Variación
			isDefault
			relationship: 16939975-09fe-4f6d-8184-c364914ac84c
			defaultHierarchy: LocalDateTable_eb877397-1919-4449-b265-9c976c1db4e2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha frenado por el cliente'
		dataType: dateTime
		formatString: Short Date
		lineageTag: e767eee8-f892-442c-a7e8-56ec23890bbd
		summarizeBy: none
		sourceColumn: Fecha frenado por el cliente

		variation Variación
			isDefault
			relationship: 6e3dd99a-bfcd-487f-a471-5974e6209f1a
			defaultHierarchy: LocalDateTable_8bfdca5e-ae39-48fd-8672-f9c84ce9c7c4.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha sin respuesta'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2ba371b5-1c2a-4651-811f-b473aadbc54d
		summarizeBy: none
		sourceColumn: Fecha sin respuesta

		variation Variación
			isDefault
			relationship: 972eda5b-1fdc-42a6-87b8-d61c68e32857
			defaultHierarchy: LocalDateTable_665e79e0-72f3-4436-a269-2dc050af8c28.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de Baja'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8d6226e9-179a-4c88-a205-d58d77125df1
		summarizeBy: none
		sourceColumn: Fecha de Baja

		variation Variación
			isDefault
			relationship: 1fe8a120-7288-487d-86c2-0b240b3d0375
			defaultHierarchy: LocalDateTable_d00ddfcf-fbe9-4237-a359-6006bd5d9708.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 6e20e403-a501-4e62-9850-4c5050567f9c
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column whatsapp
		dataType: string
		lineageTag: e4654cc1-e344-4f77-9559-495df3c7133a
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: whatsapp

		annotation SummarizationSetBy = Automatic

	column Tags
		dataType: string
		lineageTag: b55e8735-bef2-439f-8dfb-b201f6a399ef
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	column Licencia
		dataType: string
		lineageTag: 94476285-8642-4fd6-b773-59110912e472
		summarizeBy: none
		sourceColumn: Licencia

		annotation SummarizationSetBy = Automatic

	partition 'IMPLEMENTACION BOARD' = m
		mode: import
		source =
				let
				    Origen = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1YO-TTEIbO7QkeiBrd9zqSHUV4W2aO7FDsfts4G_ZTBI/edit?usp=sharing"),
				    #"IMPLEMENTACION BOARD_Table" = Origen{[name="IMPLEMENTACION BOARD",ItemKind="Table"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"IMPLEMENTACION BOARD_Table", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"ID", Int64.Type}, {"Title", type any}, {"Work Item Type", type text}, {"State", type text}, {"Cliente", type text}, {"Plan Contratado", type text}, {"Seniority", type text}, {"Rubro", type text}, {"Persona de Contacto", type text}, {"Telefono de Contacto", type text}, {"Board Column", type text}, {"Fecha de Contratacion", type datetime}, {"Fecha de Inicio", type datetime}, {"Fecha inicio Fase 1", type datetime}, {"Fecha Implementado", type datetime}, {"Fecha frenado por el cliente", type datetime}, {"Fecha sin respuesta", type datetime}, {"Fecha de Baja", type datetime}, {"Description", type text}}),
				    #"Personalizada agregada" = Table.AddColumn(#"Tipo cambiado", "whatsapp", each "https://wa.me/+54" & [Telefono de Contacto]),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Personalizada agregada",{"ID", "Title", "Work Item Type", "State", "Telefono de Contacto"}),
				    #"Personalizada agregada1" = Table.AddColumn(#"Columnas quitadas", "Licencia", each [Tags])
				in
				    #"Personalizada agregada1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

